### ISSUE TITLE
캠페인의 데이터를 다운로드 할 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#116]
서명이 있는 경우는 서명 데이터 다운로드 버튼도 넣구요.

**Comment by dalikim** [comment]
우선 댓글에 개인정보 제공 동의여부를 기록해야하는 이슈 #117 와 함께 처리해야합니다.

**Comment by gjkimpam** [comment]
확장자 .xlsx 로 다운로드는 가능하나, 파일을 열었을 때 아무 데이터도 안 뜹니다.

**Comment by dalikim** [comment]
@gjkimpam 재현할 수 있게 정보를 더 주세요.

**Comment by gjkimpam** [comment]
> @gjkimpam 재현할 수 있게 정보를 더 주세요.

다시 해봤는데, 데이터 잘 보이네요. 이슈 없습니다.
