### ISSUE TITLE
답변한 의원에게는 개별촉구 버튼은 숨깁니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#123]

**Comment by gjkimpam** [comment]
'재활용되지 않는 일회용 컵, 보증금 제도가 필요합니다🙋‍♀'에서 봤을 때, 
- 찬성 답변한 한정애 의원의 개별촉구 버튼은 숨겨져 있지만,
- 답변한 김동철 의원의 버튼은 그대로 보입니다.

[촉구 응답 현황]
![스크린샷 2019-12-04 오후 7 54 23](https://user-images.githubusercontent.com/35594166/70176247-10daba00-16d0-11ea-8963-9037ff795e25.png)
[촉구하기]
![스크린샷 2019-12-04 오후 7 54 17](https://user-images.githubusercontent.com/35594166/70176245-10daba00-16d0-11ea-9713-34544cae5a7a.png)

**Comment by dalikim** [comment]
@gjkimpam 답변은 했지만 찬반을 표시하지 않아서 촉구 버튼이 활성화되어야 합니다.
