### ISSUE TITLE
캠페인의 조회수가 업데이트됩니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#124]

**Comment by gjkimpam** [comment]
참여건수나 달성률은 보이는데, 조회수는 어디서 확인할 수 있는지 찾아봐도 잘 안 보이네요. 
참고할 수 있는 링크나 해당 영역 캡쳐해서 공유 부탁드려요.

**Comment by dalikim** [comment]
@gjkimpam https://campaigns.kr/campaigns/173 여기서 확인해주세요. 캠페인의 종류에 따라 숨겨진 경우가 꽤 됩니다.

**Comment by gjkimpam** [comment]
네, 확인했습니다. 추모하기에서는 잘 보입니다. 
https://campaigns.kr/campaigns/193
