### ISSUE TITLE
메인 키비주얼 영역 수정 제안 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#129]
1. '참여하기' 버튼 뿐만 아니라 키 비주얼 영역 전체나 제목에 마우스를 갖다 댈 때도 캠페인 상세 페이지로 이동하면 어떨까 싶습니다.  (예시: [아바즈](https://secure.avaaz.org/page/kr/))

2. 키 비주얼 영역에 2개 이상의 캠페인이 올라갈 경우, (자동) 슬라이드로 보이면 좋을 것 같아요. 주요 캠페인을 한꺼번에 살펴볼 수 있어서요.  

![스크린샷 2019-11-26 오후 2 50 35](https://user-images.githubusercontent.com/35594166/69644375-7be71980-105c-11ea-80bc-39b8d82330ce.png)

예시) 
1. ![스크린샷 2019-11-26 오후 2 53 03](https://user-images.githubusercontent.com/35594166/69644391-7e497380-105c-11ea-98fc-a083912af0d7.png)
2. ![스크린샷 2019-11-26 오후 2 56 25](https://user-images.githubusercontent.com/35594166/69644922-3aa33980-105d-11ea-8ff3-10fdfcfb930d.png)

**Comment by dalikim** [comment]
이슈를 둘로 나눠 주세요. @gjkimpam

**Comment by gjkimpam** [comment]
자동 슬라이드 제안은 #140 으로 옮겼습니다.
