### ISSUE TITLE
사용자가 에디터를 조금 더 쉽게 쓸 수 있는 방법을 모아봅니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#134]
(참여연대 별밤&계정 님 만나서 들었던 아이디어&제안 공유드려요) 별밤 님이 캠페인즈 에디터가 쓰다 보니까 익숙해지는데, 처음 쓰시는 분들은 불편함을 느낄 수 있겠다는 생각이 든다고 합니다. 저도 동의해서 어떤 부분에서 개선되면 좋을지 모아보고, 실제 적용하면 좋을 것을 추려보면 좋겠어요. 

- 자세히 읽어보면 어떤 항목을 입력하면 되는지 적혀있는데 뭔가 익숙하지 않은 게 있대요. 예를 들어, 이미지 사이즈 가이드나 모바일에서는 잘 보이는지 등의 추가 안내가 있으면 좋을 것 같다고 하십니다. 

- 서명하기는 특히 입력항목이 긴데, 기본정보와 추가기능을 쪼개서 두 영역으로 나누면 어떨까요. 아니면 [타입폼](https://www.typeform.com/)처럼 답변할 것을 하나씩만 보여주는 애니메이션 같은 기능이 있어도 좋을 것 같아요. 

- 레이블& 가이드 문구 중 분명하지 않은 것(예: '비워두면 적절히 표시됩니다.', 'CSS 스타일')을 모아서 정리해봐도 좋겠습니다.

**Comment by rest515** [comment]
개설 프로세스 개선시에 고려하기로 하고 이 이슈는 닫겠습니다.
