### ISSUE TITLE
임시저장 개선 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#138]
캠페인 개설창 자체에 입력할 것들이 많아서 이 임시저장 안내가 눈에 잘 안 들어오는 것 같아요. 
![스크린샷 2019-12-04 오후 8 27 11](https://user-images.githubusercontent.com/35594166/70178669-952f3c00-16d4-11ea-83da-c3fc7734601e.png)

- 시작일(선택) 근처에 마우스가 갈 때, 팝업 안내가 간다거나 
- 가장 직관적으로 저장 버튼 옆에 '임시저장' 버튼이 따로 마련되는 것이 좋을 것 같아요.

**Comment by rest515** [comment]
개설 프로세스 개선시에 같이 고려하기로 하고 이 이슈는 닫을께요.
