### ISSUE TITLE
메인 하단에 '개인정보취급방침'을 '개인정보처리방침'으로 수정합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#139]
메인 하단에 '개인정보**취급**방침'으로 되어 있는 것을 '개인정보**처리**방침'으로 수정합니다. 

<img width="955" alt="스크린샷 2019-12-02 오후 8 29 02" src="https://user-images.githubusercontent.com/35594166/69992809-68e3b600-1542-11ea-991a-bddf540bee86.png">

**Comment by rest515** [comment]
간단한 작업이라 마스터에 바로 푸시했습니다. @dalikim @iamswain25
