### ISSUE TITLE
키 비주얼 영역에 2개 이상의 캠페인이 올라갈 경우, (자동) 슬라이드로 보입니다.

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#140]
키 비주얼 영역에 2개 이상의 캠페인이 올라갈 경우, (자동) 슬라이드로 보이면 좋을 것 같아요. 주요 캠페인을 한꺼번에 살펴볼 수 있어서요.  

현재: 
![스크린샷 2019-11-26 오후 2 50 35](https://user-images.githubusercontent.com/35594166/69644375-7be71980-105c-11ea-80bc-39b8d82330ce.png)

예시: 
1. 앰네스티 코리아
![스크린샷 2019-11-26 오후 2 53 03](https://user-images.githubusercontent.com/35594166/69644391-7e497380-105c-11ea-98fc-a083912af0d7.png)
2. 청년허브
![스크린샷 2019-11-26 오후 2 56 25](https://user-images.githubusercontent.com/35594166/69644922-3aa33980-105d-11ea-8ff3-10fdfcfb930d.png)

**Comment by rest515** [comment]
현재는 아주 단순하게 접속 할 때 임의의 캠페인 하나만 보여주고 있습니다. 따라서 슬라이드가 당장 필요할 것 같진 않으니, 이 이슈도 일단 닫을께요.
