### ISSUE TITLE
1기능 서비스 패턴에 따라 메인의 목록을 캠페인 목록으로 대체해 봅니다.

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#143]

**Comment by rest515** [comment]
@iamswain25 @dalikim 이 작업을 진행할까요?

**Comment by rest515** [comment]
@dalikim @iamswain25 @wagurano 검토 부탁드립니다.

**Comment by dalikim** [comment]
모든 캠페인 목록 리스트를 페이징으로 표시해 봤습니다. https://dev.campaigns.kr

**Comment by dalikim** [comment]
> 모든 캠페인 목록 리스트를 페이징으로 표시해 봤습니다. https://dev.campaigns.kr

보시고 의견 주셔요.

**Comment by iamswain25** [comment]
차이가 크게 느껴지진 않습니다. 개인적으로 페이징 보다 검색 & 스크롤 레이지로딩을 선호하는데, 국회의원이 걸리네요. 국회의원 명단이 첫 화면에 꼭 보여야 한다면 각 캠페인 란에 대표 의원 3명 사진 +숫자로 보여주는건 어떨까요?

**Comment by dalikim** [comment]
> 차이가 크게 느껴지진 않습니다. 개인적으로 페이징 보다 검색 & 스크롤 레이지로딩을 선호하는데, 국회의원이 걸리네요. 국회의원 명단이 첫 화면에 꼭 보여야 한다면 각 캠페인 란에 대표 의원 3명 사진 +숫자로 보여주는건 어떨까요?

1. 아시다시피 무한 스크롤 방식은 UX에서 논란이 많은 부분이죠. 사용성을 헤친다 아니다. 등등. 되려 저는 여기 무한스크롤이 반드시 필요할까 묻고 싶습니다. 페이징이 별로라면 더보기 버튼 정도가 어떨까 싶네요.
2. 국회의원 명단이 첫 화면에 **꼭** 보일 필요는 없구요. 있으면 좋겠다입니다. 제안하신 캠페인 마다 대표의원 보이는것도 급한 건 아닐 것 같습니다.

**Comment by rest515** [comment]
구조가 심플해져서 좋네요. 페이지를 하나라도 줄이는게 저는 엄청나게 큰 (긍정적인) 변화로 보입니다. 

캠페인즈는 페이지수를 더 하나라도 줄이고, 거꾸로 캠페인 기능은 더 단순하면서도 강력하게 만들었으면 좋겠습니다. 오늘 이슈들을 좀 정리해 볼께요.

**Comment by dalikim** [comment]
@iamswain25 @rest515 그렇다면 페이징이 좀 걸리긴 하지만 앞으로 발전할 것을 기대하면서 애자일하고 빠른 배포를 위해 지금 실서버에 올려 보겠습니다.
