### ISSUE TITLE
소셜네트워크서비스(SNS)로 회원가입시, 개인정보처리방침과 이용약관 링크를 수정합니다. 

### ISSUE THREAD

**Issue by gjkimpam** [parti-coop/govcraft#145]
우연히 발견했어요. @iamswain25 확인 부탁드려요. 
- [x] 페이스북으로 회원가입 
- (캠페인즈) 개인정보 처리방침 클릭시, https://parti.xyz/privacy
- (캠페인즈) 이용약관 클릭시, https://parti.xyz/terms

- [x] 트위터로 회원가입 
- (캠페인즈) 개인정보 처리방침 클릭시, https://parti.xyz/privacy
- (캠페인즈) 이용약관 클릭시, https://parti.xyz/terms

참고
- 페이스북  
![캠페인즈_페이스북 가입](https://user-images.githubusercontent.com/35594166/74317661-28fd4280-4dbf-11ea-8dbf-4080768e1826.png)
- 트위터 
![캠페인즈_트위터 가입](https://user-images.githubusercontent.com/35594166/74317671-2bf83300-4dbf-11ea-99f4-216e4f396437.jpg)

**Comment by iamswain25** [comment]
@gjkimpam 찐쩐님 개인정보처리방침 링크는 캠페인즈로 링크 안걸고 그룹스로 걸라는 뜻인가요? 페이스북과 트위터는 계정 접근에 IP를 확인해서, 제가 공통 계정으로 확인이 안되거든요. 찐쩐님과 세션을 잡아서 확인해야 할 것 같아요.

**Comment by gjkimpam** [comment]
> @gjkimpam 찐쩐님 개인정보처리방침 링크는 캠페인즈로 링크 안걸고 그룹스로 걸라는 뜻인가요? 페이스북과 트위터는 계정 접근에 IP를 확인해서, 제가 공통 계정으로 확인이 안되거든요. 찐쩐님과 세션을 잡아서 확인해야 할 것 같아요.

방금 서원님과 세션으로 해당 부문 보여드리고 이야기 나눴습니다.

**Comment by iamswain25** [comment]
@dalikim 달리님 

1. 페이스북 공통계정 비번이 lastpass에서 사라졌어요.
2. 페이스북 개발자 계정에서 govcraft 프로젝트에 swain@parti.xyz 추가바랍니다.
3. 트위터 계정도 swain@parti.xyz 로 조직 및 프로젝트에 추가 바랍니다.
4. 트위터 계정이 혹시 조직으로 추가가 되지 않으면 직접 수정 부탁드립니다. 제가 라스트패스 공통계정으로도 핸드폰 인증이 안돼서요.

https://campaigns.kr/terms
https://campaigns.kr/privacy

두 링크로 수정하시면 됩니다!

**Comment by dalikim** [comment]
제 기억이 틀릴 수 있는데 페북은 공통계정이 없어요. 페북에서 사람이 아닌 법인이 활동하면 이용약관에 어긋나는 걸로 알아요. 해서 개발자 계정은 개발자 모두 관리자가 등록되어 있답니다.

이참에 등록 진행하면 되겠네요.

> @dalikim 달리님
> 
> 1. 페이스북 공통계정 비번이 lastpass에서 사라졌어요.
> 2. 페이스북 개발자 계정에서 govcraft 프로젝트에 [swain@parti.xyz](mailto:swain@parti.xyz) 추가바랍니다.
> 3. 트위터 계정도 [swain@parti.xyz](mailto:swain@parti.xyz) 로 조직 및 프로젝트에 추가 바랍니다.
> 4. 트위터 계정이 혹시 조직으로 추가가 되지 않으면 직접 수정 부탁드립니다. 제가 라스트패스 공통계정으로도 핸드폰 인증이 안돼서요.
> 
> https://campaigns.kr/terms
> https://campaigns.kr/privacy
> 
> 두 링크로 수정하시면 됩니다!

**Comment by dalikim** [comment]
> 페이스북 개발자 계정에서 govcraft 프로젝트에 swain@parti.xyz 추가바랍니다.

<img width="496" alt="스크린샷 2020-02-29 12 52 50" src="https://user-images.githubusercontent.com/1650024/75600419-80571e80-5af2-11ea-94bc-d005d4ee93f1.png">

페이스북 계정 정보를 다시 주세요.

> 3\. 트위터 계정도 [swain@parti.xyz](mailto:swain@parti.xyz) 로 조직 및 프로젝트에 추가 바랍니다.

트위터에 팀이 최근에 생겼군요. 전에 없었는데. 근데 초대해도 작동하지 않는 듯해요. 살펴볼 시간이 없는데요. 혹시 휴대폰 인증 과정을 저랑 함께 페어해서 확인해 볼 수 있을까요?

**Comment by iamswain25** [comment]
@dalikim 페이스북은 메일이 아니라 유저네임으로 등록해야하군요. `swain.parti` 입니다. 트위터는 페어해서 같이 보시죠.

**Comment by dalikim** [comment]
@iamswain25 페이스북은 초대드렸습니다.
