### ISSUE TITLE
캠페인 시작하는 프로세스를 점검하고 개선합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#146]

**Comment by rest515** [comment]
![image](https://user-images.githubusercontent.com/794973/74404261-4d175d00-4e6d-11ea-85b4-a91bd7745dcb.png)

이 페이지와 다음 단계 폼을 개선하면 좋겠는데요. @Mee-parti @iamswain25 같이 고민해 보실까요?

**Comment by dalikim** [comment]
@wagurano 님과 함께 이야기해보실래요? 전에 진행하시던게 있어요.

**Comment by rest515** [comment]
오호 좋습니다. @wagurano 님 혹시 어떻게 진행되고 있는지 나눠 주실 수 있을까요?

**Comment by dalikim** [comment]
참고 삼아만 봐주세요.


https://drive.google.com/drive/folders/1cPTYd65Zjc8rzpApsT5O9tBz0ctOnhNW

![70699-38](https://user-images.githubusercontent.com/1650024/74405063-8ea90780-4e6f-11ea-86d0-f62094d4d015.png)

![70699-41](https://user-images.githubusercontent.com/1650024/74405081-9c5e8d00-4e6f-11ea-9d7a-cc2c58825437.png)

![70699-42](https://user-images.githubusercontent.com/1650024/74405100-a7192200-4e6f-11ea-9277-44081ea23ac6.png)

![70699-43](https://user-images.githubusercontent.com/1650024/74405114-ad0f0300-4e6f-11ea-9df7-99b731aa1273.png)


![70699-45](https://user-images.githubusercontent.com/1650024/74405202-da5bb100-4e6f-11ea-886c-72d23cccbd09.png)


![70699-47](https://user-images.githubusercontent.com/1650024/74405221-e6477300-4e6f-11ea-90c2-a393ba8bf29f.png)

**Comment by rest515** [comment]
오.. 좋네요.

**Comment by iamswain25** [comment]
https://app.moqups.com/WuuEWA5hPc/view/page/ab53f1d4f
찐쩐님이 작업해주신 개인정보처리방침 변경 건도 위 기획에 반영이 되어야 할 것 같은데요. 한 번에 다 하려면 시간이 많이 걸릴 것 같습니다. 개인정보처리방침은 제가 먼저 처리 할게요.

**Comment by rest515** [comment]
네 달로스님 확인해주시는 대로 이 이슈 작업 시작하면 좋겠습니다.

1) 위저드 기능 방식으로 하는 것 좋습니다. 다만 이슈를 지정하는 기능은 이번엔 생략하면 어떨까 합니다. 바로 생성 단계로 넘어가는 것으로
2) 어떤 방식의 캠페인이 생성 가능한지 기획서와 현재 서비스가 상이한데요. 혹시 무엇이 맞는 건지 확인해 주실 수 있을까요? @dalikim

**Comment by dalikim** [comment]
> 2. 어떤 방식의 캠페인이 생성 가능한지 기획서와 현재 서비스가 상이한데요. 혹시 무엇이 맞는 건지 확인해 주실 수 있을까요? @dalikim

이건 저도 조금 과거를 복기해봐야해요. 1년이나 된 기획이거든요. 그치만 복기하기 힘든 일은 아니구요. 제가 오늘 오프인지라 그래요. 혹시 이번 주말을 기다려 주실 수 있나요? 주말 동안 찬찬히 정리해 볼께요. 기획 리딩했던 수진님 도움도 받아야 할 수도 있어요.

**Comment by dalikim** [comment]
추가해서 이야기하면 캠페인 만들때 뿐만 아니라 서비스 전반에서 이슈를 좀더 숨겨도 좋겠습니다.

> 1. 위저드 기능 방식으로 하는 것 좋습니다. 다만 이슈를 지정하는 기능은 이번엔 생략하면 어떨까 합니다. 바로 생성 단계로 넘어가는 것으로

**Comment by rest515** [comment]
네 좋습니다. 제가 궁금한 점을 조금 더 명확히 하면.. 기획에서는 서명하기, 팻말들기, 추모하기 세가지인데.. 현재 서비스는 6가지여서요. ㅎㅎ 어떤게 맞는건지 궁금합니다.

**Comment by dalikim** [comment]
> 네 좋습니다. 제가 궁금한 점을 조금 더 명확히 하면.. 기획에서는 캠페인 템플릿이 서명하기, 팻말들기, 추모하기 세가지인데.. 현재 서비스는 6가지여서요. ㅎㅎ 어떤게 맞는건지 궁금합니다.

당시 기획에서 6개란 숫자가 너무 복잡해서 3개 이하로 줄이는걸 목표로 했습니다. 대신 위저드로 들어가서 상세설정을 통해 결국 모든 타입을 지원하게 만들 요량이었죠.

**Comment by Mee-parti** [comment]
저도 서비스를 3개정도로 간단히 보여주는 게 좋을 것 같아요. 6가지 서비스 중에 어떤 매체(글, 사진, 링크 등)를 활용하느냐에 따라서도 묶일 수 있을 거라 생각되요. 예를 들면 서명하기, 촉구하기는 글의 길이 차이로 다르게 볼 수 있고, 인증샷과

**Comment by Mee-parti** [comment]
저 캠페인즈에서 진행하는 캠페인들 분석하고 있는데, 6가지 기능 중에 목소리 모으기와 팻말들기가 혼용되고 있는 것 같다는 생각이 드네요. 예를 들면 제가 캠페인 소개할 때 차별잇수다를 목소리 모으기로 이야기 했는데, 팻말들기 였어요 헛! 목소리 모으기 기능와 팻말들기 차이를 알고 싶어요.

**Comment by dalikim** [comment]
> 저 캠페인즈에서 진행하는 캠페인들 분석하고 있는데, 6가지 기능 중에 목소리 모으기와 팻말들기가 혼용되고 있는 것 같다는 생각이 드네요. 예를 들면 제가 캠페인 소개할 때 차별잇수다를 목소리 모으기로 이야기 했는데, 팻말들기 였어요 헛! 목소리 모으기 기능와 팻말들기 차이를 알고 싶어요.

**현재 모습**

서명받기 / 촉구하기 / 목소리 모으기 / 인증샷 모으기 / 지도 모으기 / 추모하기

**1년 전 기획 안**

* 서명하기 
  * 서명 받기와 동일
  * 캠페인 참여자가 촉구할 수 있게 캠페인 만들기 위자드에서 옵션 제공
* 팻말들기
  * 기본 팻말들기는 목소리 모으기를 대체
  * 캠페인 참여자가 사진을 올릴 수 있게 캠페인 만들기 위자드에서 옵션 제공하여 기존 인증샷 모으기를 대체
  * 캠페인 참여자가 지도 위치를 올릴 수 있게 캠페인 만들기 위자드에서 옵션 제공하여 기존 지도 모으기를 대체
  * 캠페인 참여자가 촉구할 수 있게 캠페인 만들기 위자드에서 옵션 제공하여 기존 촉구하기를 대체
* 추모하기
  * 기존 추모하기와 동일

**Comment by rest515** [comment]
네네 저는.. 정리해주신 걸 바탕으로 생각한다면, 저는 여러 옵션들을 사용자들이 선택하기보단 유형별로 옵션이 선택된 방식으로 만들게 하는게 좋을 것 같아요. 그러니까 지금 6개 정도로 풀어놓은게 더 좋은 것 같구요.

각 유형별로 설명이 좀 더 들어가고, 실제 사례를 링크를 걸어서 뭔지 확인할 수 있는 페이지로 시작하면 어떨까 합니다.

1. 서명하기: 설명과 예시 사진, 그리고 예시로 가는 링크
2. 서명과 함께 촉구하기: 설명과 예시 사진, 그리고 예시로 가는 링크
3. 목소리 모으기: 설명과 예시 사진, 그리고 예시로 가는 링크
4. 사진과 함께 목소리 모으기: 설명과 예시 사진, 그리고 예시로 가는 링크
5. 사진과 함께 목소리 모으며 촉구하기: 설명과 예시 사진, 그리고 예시로 가는 링크
6. 추모하기: 설명과 예시 사진, 그리고 예시로 가는 링크

좀 주절주절이지만.. 이렇게 시작 페이지를 고쳐보면 어떨까요?

**Comment by dalikim** [comment]
> 네네 저는.. 정리해주신 걸 바탕으로 생각한다면, 저는 여러 옵션들을 사용자들이 선택하기보단 유형별로 옵션이 선택된 방식으로 만들게 하는게 좋을 것 같아요. 그러니까 지금 6개 정도로 풀어놓은게 더 좋은 것 같구요.

6개로 풀어 놓은 것은 현재 정리되지 않은 모습이 자꾸 떠오르고
3개로 묶은 것은 잘 정리된 모습이 떠오는지라 날카로운 판단은 어렵네요.

1. 캠페인 만들 때 단순한 느낌이 들게 하자는 취지엔 동의하고요.
2. 위저드 방식이 아주 잘 설계하면 좋긴한데요. 개발 노력 대비 얻는게 많을지 계산이 필요한 상황이네요. 

1년 전 기획을 통해 캠페인 종류가 잘 라인업 되었다는데 의의를 두고요.
말씀하신대로 시작페이지를 고치고, 현재 캠페인 생성/수정폼을 잘 다듬어서(펼칠 것만 펼치고, 접을 건 접어서) 점진적인 개선을 시도하는게 바른 접근이라 생각합니다.

**Comment by rest515** [comment]
태그 따고 작업 시작해 보겠습니다. 필요한 컨텐츠는 미님이 정리해주시는데로 바로 반영할께요.

**Comment by rest515** [comment]
디자인 개선은 부트스트랩을 업그레이드하거나 한 다음에 진행하겠습니다. 이제 초기 캠페인 생성시 지나치게 많은 필드를 입력하는 부분을 개선해 볼께요.
