### ISSUE TITLE
스팸봇이 회원 가입을 할 수 없도록 합니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#147]
스팸봇이 회원 가입을 합니다. 이를 막도록 조치가 필요합니다.
https://campaigns.kr/campaigns/208

**Comment by Mee-parti** [comment]
우선 어제자로 올라온 스팸 기록은 지웠습니다. 회원가입 막는 조치를 취하기 전에는 매일 한번씩 관리해볼게요!

**Comment by dalikim** [comment]
> 우선 어제자로 올라온 스팸 기록은 지웠습니다. 회원가입 막는 조치를 취하기 전에는 매일 스팸에 대해선 한번씩 관리해볼게요!

회원 블랙리스트 기능 기억이 없는데요. 우선 이슈로 만들고 찬찬히 조치해볼께요.  #149
