### ISSUE TITLE
팻말 작성시 사진은 필수입니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#15]
사진 선택 기능이 옵션으로 설정됨
현재 사진 첨부하지 않아도 팻말 작성 가능
첨부파일 없을 경우 가크 디폴트 이미지로 업로드됨
사진 미첨부시 작성 불가하도록 수정 필요

**Comment by dalikim** [comment]
사진 미첨부해서 작성하면 사진 없는 팻말 모양이면 어떠려나요?
