### ISSUE TITLE
메일로 정보 이관 공지하기

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/govcraft#161]
약관에 따라 적어도 3월 23일 전에는 풀리퀘 배포 및 이메일 공지

**Comment by rest515** [comment]
이 작업은 끝났을까요? @Mee-parti @iamswain25

**Comment by iamswain25** [comment]
> 이 작업은 끝났을까요? @Mee-parti @iamswain25

끝났습니다. 현재까지 메일 오픈 212 명으로 20%입니다 ㅎㅎ
