### ISSUE TITLE
캠페인즈 사이트맵을 넣습니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/govcraft#174]

**Comment by rest515** [comment]
홈페이지에 사용한 방법대로 제너레이터를 추가하고 규칙도 넣었습니다. 그런데 배포시에 이게 자동으로 실행되게 해야 할 것 같은데 그건 서버 설정에 있을 것 같네요. @dalikim 님이나 @iamswain25 님이 살펴 봐 주셔요.

**Comment by dalikim** [comment]
https://search.google.com/search-console/sitemaps?resource_id=sc-domain%3Acampaigns.kr 등록 완료했습니다.
