### ISSUE TITLE
서명하기 캠페인에서 촉구를 하고 의견을 남기면, 서명하기에서 보이지 않습니다.

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#30]
촉구 의견과 서명하기가 헷깔립니다. https://govcraft.org/campaigns/167/orders 여기서 ‘서명’을 해야겠단 의도로 <16명 모두에게 촉구하기>를 누르고 의견을 남겼는데, 서명이 아니라 의견남기기가 되었네요. (쓰레기덕질 멤버로부터도 받은 적 있는 피드백)

**Comment by dalikim** [comment]
오른쪽 사이드에 촉구 현황도 보여 줄까요?
