### ISSUE TITLE
지도와 인증샷 캠페인 만들기에서 촉구 대상 지정시 촉구 페이지 오류 발생

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#31]
지도 모으기, 인증샷 모으기 캠페인 개설 후 촉구 대상을 지정했을 경우 촉구 페이지에 오류가 납니다. https://govcraft.org/campaigns/179/orders

**Comment by dalikim** [comment]
#33 과 연결된 이슈입니다. 여긴 완료할께요.
