### ISSUE TITLE
운영자 추가 페이지에서 완료후 캠페인으로 돌아갈 수 없습니다.

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#32]
운영자 추가 페이지에서 완료 후 캠페인으로 돌아가기 방법이 없습니다. https://govcraft.org/organizers?project_id=100

**Comment by dalikim** [comment]
@wagurano 프로젝트와 조직 관리자 관련해서는 기획을 좀더 정비하고 일감을 추가하면 어떨까요? 먼저 닫아 놓을께요.
