### ISSUE TITLE
목소리 모으기 캠페인, 사진 캠페인, 지도 캠페인은  촉구대상을 지정할 수 없습니다.

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#33]
추모하기 캠페인에 촉구대상 관리 메뉴가 있지만, 촉구대상을 지정해도 캠페인 콘텐츠에 변화가 없네요.

**Comment by dalikim** [comment]
우선 추모하기 캠페인과 목소리 모으기 캠페인, 사진 캠페인, 지도 캠페인은 촉구대상을 지정할 수 없도록 조치할까 합니다.

**Comment by dalikim** [comment]
다만 기존에 촉구 했던 이력이 있으니 앞으로 만들 수 없게 할께요.

**Comment by gjkimpam** [comment]
새 캠페인 에디터에서 목소리 모으기, 사진, 지도 모으기에 촉구 영역이 없는 것만 확인했습니다. 
혹 이외에 또 확인해야하는 페이지나 영역이 있으면 알려주세요.

**Comment by dalikim** [comment]
더 없습니다. @gjkimpam
