### ISSUE TITLE
추모하기 캠페인에서 의견 작성후 횟수가 증가하지 않습니다.

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#34]
추모하기 캠페인에 의견을 남겨도 참여 카운팅이 되지 않는 것 같아요. https://govcraft.org/campaigns/173#anchor-sign

**Comment by dalikim** [comment]
카운팅이 안되는게 어느 부분일까요?

**Comment by rest515** [comment]
참여자수 숫자가 올라가는 것 확인했습니다. 이 이슈는 닫을께요.
