### ISSUE TITLE
가브크래프트 다음 버전 개선 사항

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#38]
가브크래프트 다음 버전 개선 사항
-----------------------------
> 의견을 달아주면 여기에 계속 정리하겠습니다.

- 참여자 리스트 엑셀로 다운로드하기
- (개발인지 애매하지만) 캠페인마다 캠페이너가 서명을 받은 것을 내려 받을 때 개인정보보호법에 위배되는 것은 없는지, 있다면 적절한 기능 조치 취하기
- 촉구대상이 없거나, 해당 대상이 바뀐 경우에 사용자가 취할 수 있는 조치 방안을 제공하기
- 캠페인의 어지러운 태그클라우드 정리하기. 접어놓기 정도면 어떨까? https://govcraft.org/campaigns/157/pickets
- 캠페인 내용 탭 속에 유투브 미리보기와 재생 기능 담기

**Comment by rest515** [comment]
이 이슈도 닫는건 어떨까요?

**Comment by dalikim** [comment]
@rest515 @wagurano 우선 필요없어보이는 이슈는 서로 묻지말고 주욱 닫아보면 어떨까요? 다시 열면 되니까요.

**Comment by rest515** [comment]
좋습니다.
