### ISSUE TITLE
가브크래프트 추진 전략 세우기 - 명칭 변경 논의

### ISSUE THREAD

**Issue by wagurano** [parti-coop/govcraft#43]
가브크래프트 기능 가운데 '캠페인'관련 기능을 강화하기 위해 명칭을 가브크래프트에서 캠페인으로 변경할지 검토합니다.

**Comment by rest515** [comment]
"빠띠 캠페인즈"로 명칭을 수정하려고 합니다. 또한 도메인도 govcraft.org 에서 다른 도메인으로 바꿀지도 결정합니다.

**Comment by rest515** [comment]
캠페인즈로 명칭 변경을 한번 해 볼께요. 도메인도 변경하는게 좋을까요?

**Comment by wagurano** [comment]
도메인 이름으로 campaigns.kr 이나 이와 비슷한 도메인 이름으로 바꾸는 건가요?

**Comment by rest515** [comment]
넵. townhall.kr 처럼, 도메인도 campaigns.kr 로 바꾸는게 어떨까 합니다.

**Comment by wagurano** [comment]
다른 이름으로 캠페인을 캠프로 줄여서 몇가지 찾아봤는데 베이스캠프만 떠오르네요.
트위터가 t.co를 쓰듯이 축약주소는 필요하지 않을까요?

**Comment by rest515** [comment]
축약주소도 있으면 좋겠네요. 어떤게 좋을까요?

**Comment by wagurano** [comment]
막상 짧으면서 등록할 수 있는 도메인 이름을 찾기 어렵네요. bit.ly와 같은 서비스를 활용해야겠습니다.

**Comment by dalikim** [comment]
* 도메인 구매 설치했습니다.
* SSL 키를 새로 발급 받았습니다.
* 메일 계정을 새로 땃습니다. contact@campaigns.kr
* 구글 그룹스 만들고 크루 중에 캠페이너들과 @wagurano @rest515 님 초대 했습니다
* Aws SES 설정을 했습니다.
* 소스에 메일 주소랑 링크 들도 손봤습니다.
* 새로운 주소에 맞춰 서버 설정을 손봤습니다.
* 트위터랑 페북에 들러서 로그인 설정 바꿨습니다.

** 외부 연동되는게 몇 개 있어어서 구 주소는 그냥 둡니다. 파악해서 옮기든지 해야하는데요. 논의해봐요. **
그래서 오늘은 https://govcraft.org 첫 페이지만  https://campaigns.kr 로 redirct하고 나머지는 다른 일감으로 며칠 동안 슬슬 해볼까해요. 의견 주세요.

**Comment by gjkimpam** [comment]
캠페인즈로 플랫폼 명칭이 변경된 것 관련해 공지하고 리브랜딩(변경한 이유와 캠페인즈 명칭의 의미가 들어간) 콘텐츠가 나오면 좋겠네요.

**Comment by dalikim** [comment]
아직은 몰래 하고 싶은데 ㅋㅋ ( 반 농입니다 )

**Comment by rest515** [comment]
우선 이 이슈는 마무리할께요~
