### ISSUE TITLE
개인정보처리 방침에 대해 법적 검토가 필요합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#47]
협력하는 모 단체 중에 개인정보 문제를 다루는 곳에서 개선 요구가 들어왔습니다. 조속히 처리 되어야겠습니다.
- [x] 개인정보처리 방침에 대해 검토
- [x] 캠페인별 개인정보처리 방침 방식에 대한 검토

**Comment by dalikim** [comment]
개인정보처리 방침을 다시 작성하는걸 진행하고 싶습니다. @gjkimpam @anne-parti  진행을 부탁드리고 싶은데요. 언제 가능할까요? 어떤 자원이 필요할까요?

**Comment by dalikim** [comment]
캠페인별 개인정보처리 방침 방식에 대한 검토는 박지환 변호사님께 메일을 보냈습니다.

**Comment by dalikim** [comment]
변호사님으로 부터 받은 자문 결과입니다.
 
> 보내주신 질의 내용은
참여자로 부터 "빠띠"(플랫폼 운영자)가 수집한 참여자의 개인정보를 제3자(캠페인 개설자)에게 제공할 수 있는지로 이해하였습니다.
> 원칙적으로는 
>
> (1) 제3자(캠페인 개설자)가 직접 참여자로부터 개인정보 수집 이용동의를 받거나
(2) 빠띠(플랫폼 운영자)가 개인정보 수집 이용동의를 받을 때 "제3자제공"동의를 받는 두가지 방법이 있습니다.
>
> 현재 개인정보수집이용 동의는 제3자(캠페인 개설자)가 직접 참여자로부터 개인정보 수집 이용동의를 받는 첫번째 방법인 것 같은데,
> 
> "차별금지법제정연대는 본 캠페인을 위해 이메일을 수집하고 있습니다. 수집된 개인정보는 정당 회신 및 관련 소식을 전하는 데 사용됩니다. 
수집된 정보는 차별금지법제정연대에서 관리합니다. (문의 : equalact2017@gmail.com) "
> 
> 위 개인정보처리방침에 동의하는 현재 방식으로는 부족하며 아래 4가지 항목을 모두 고지하고 동의를 받으셔야 합니다.
> 
> ② 개인정보처리자는 제1항제1호에 따른 동의를 받을 때에는 다음 각 호의 사항을 정보주체에게 알려야 한다. 다음 각 호의 어느 하나의 사항을 변경하는 경우에도 이를 알리고 동의를 받아야 한다.
> 
> 1. 개인정보의 수집ㆍ이용 목적
> 
> 2. 수집하려는 개인정보의 항목
>
> 3. 개인정보의 보유 및 이용 기간
>
> 4. 동의를 거부할 권리가 있다는 사실 및 동의 거부에 따른 불이익이 있는 경우에는 그 불이익의 내용
>
>
> 자세한 내용은 아래 링크의 첨부파일 확인 부탁드립니다.
> 
> https://www.mois.go.kr/frt/bbs/type010/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000008&nttId=56809

**Comment by wagurano** [comment]
덧붙임: "개인정보를 제공받는 자(기관명, 담당자명, 연락처)" 항목도 같이 표시하면 좋겠습니다.
다만, 제3자 제공 동의하여만 팻말들기, 촉구하기를 등록할 수 있도록 할지 조금 고민됩니다.

**Comment by dalikim** [comment]
@wagurano 
> 덧붙임: "개인정보를 제공받는 자(기관명, 담당자명, 연락처)" 항목도 같이 표시하면 좋겠습니다.
> 다만, 제3자 제공 동의하여만 팻말들기, 촉구하기를 등록할 수 있도록 할지 조금 고민됩니다.

개인정보를 제공을 동의하지 않았을 경우 해당 팻말 시민의 정보는 제공하지만 않으면 됩니다.
좀더 의견 나눠보고 관련 기능 + 안내문? 정리하면 합니다.

**Comment by gjkimpam** [comment]
방침 업데이트시, 
메인 하단에 '개인정보**취급**방침'으로 되어 있는 것을 '개인정보**처리**방침'으로 수정합니다. 

<img width="955" alt="스크린샷 2019-12-02 오후 8 29 02" src="https://user-images.githubusercontent.com/35594166/69992809-68e3b600-1542-11ea-991a-bddf540bee86.png">

**Comment by dalikim** [comment]
이것도 일감을 추후 나눠 올리시겠죠? @gjkimpam  닫을께요.
