### ISSUE TITLE
브랜치 운영 방식 변경 제안

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#52]
일감마다 브랜치를 따서 작업하면 어떨까요?
일감 브랜치의 명은 명확하게 어떤 일감인지 드러나는 방식으로 한다 정도만 약속하고요. 일감 브랜치의 작업이 완료되거나 중간에라도 리뷰/도움이 필요하면 pull request를 날려서 한 명 이상의 코드리뷰를 받으면 합니다. @ 멘션을 해도 좋겠네요.

master에 PR이 merge되면 자동으로 배포되게 설정할 수도 있겠습니다.

**Comment by rest515** [comment]
저는 찬성합니다.

**Comment by wagurano** [comment]
루비 언어 소개 페이지(영문 및 번역)도 비슷하게 운영하네요. https://github.com/ruby/www.ruby-lang.org/wiki/Deployment 헤로쿠를 쓴다는 점이 조금 다르지만.

**Comment by dalikim** [comment]
아 좋습니다.

우연치 않게 저의 의견과 똑같은 잘 정리된 글을 찾아 공유합니다.

소규모 팀
https://gmlwjd9405.github.io/2017/10/27/how-to-collaborate-on-GitHub-1.html

대규모 팀
https://gmlwjd9405.github.io/2018/05/12/how-to-collaborate-on-GitHub-3.html

저는 소규모 팀 방식으로 운영하되 "대규모 팀"의 핫픽스 방식을 차용하면 합니다.

**Comment by rest515** [comment]
이 이슈는 같이 모여서 한번 논의를 해 보는 것으로 마무리하면 될까요?
