### ISSUE TITLE
짧은 도메인명이 필요합니다. camz.kr 는 어떨까요?

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#56]
<img width="1250" alt="스크린샷 2019-09-26 06 38 38" src="https://user-images.githubusercontent.com/1650024/65641648-515eed00-e028-11e9-8151-e45e19e5be39.png">

**Comment by rest515** [comment]
오 좋네요.

**Comment by dalikim** [comment]
오호 그럼 구매할께요~

**Comment by rest515** [comment]
단축 URL 혹시 구매하셨으려나요?

**Comment by dalikim** [comment]
실제 코딩하기 전에 구매합니다.

**Comment by rest515** [comment]
네네 구매해주시면 제가 작업할 수 있을 듯 합니다.
