### ISSUE TITLE
파비콘과 소셜 공유 이미지, 기본 이미지에서 기존 도메인 흔적을 지웁니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#58]

**Comment by rest515** [comment]
변경하였습니다. 이 건은 풀 리퀘스트로 작업하지 않았습니다. 검토 부탁드려요.

**Comment by wagurano** [comment]
빠띠 아이콘을 활용하셨군요. 좋습니다.
seo 파일 배경색을 그라디에이션 주고 싶긴 하였는데. 지금도 좋습니다.

**Comment by dalikim** [comment]
빠띠 아이콘을 활용한 것은 이견 없긴해요. 다만 이미지 가로 세로 크기가 마음에 걸리네요. 제가 있다가 수정해 볼께요.
