### ISSUE TITLE
프로필페이지(개인)

### ISSUE THREAD

**Issue by xeno-xeno** [parti-coop/govcraft#6]
썸네일/닉네임/ 소개
/관심분야/스킬/ SNS링크
/메세지(email) 보내기

* 스킬에 따른 뱃지 시스템 고려

**Comment by dalikim** [comment]
메세지(email) 보내기는 뭔가요?

**Comment by xeno-xeno** [comment]
form mail 형태로 사용자에게 메세지 전달하는 단순 기능인데,
기존에 가브크래프트에 개발되어 있다고 시스님이 말씀하셔서 구체적인 설명은 생략했습니다. 
그런데, 메세지 보내기 화면이 어떻게 구성되어 있는지 궁금하네요 +_+

**Comment by dalikim** [comment]
아 제가 모르는 기능이 있었나 보군요 ㅋㅋ

**Comment by rest515** [comment]
아 회원에게 메시지 보내는 기능은 아니고, 국회의원에게 메시지 보내는 기능을 이야기 드렸었어요.

**Comment by xeno-xeno** [comment]
아 그렇군요. 그럼 국회의원에게 보내는 기능을 그대로 개인프로필에 적용할 순 없나요?
어차피 form mail 형태일 듯 한데.

**Comment by dalikim** [comment]
네네 적용가능하죠. 어떤 기능인지 이해했습니다.
