### ISSUE TITLE
캠페인의 홈과 메뉴를 더 간략하게 바꾸는 건 어떨까요? 

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#69]
이 이슈와도 연결이 됩니다만. https://github.com/parti-coop/govcraft/issues/62

지난번 워크숍 때 이야기나온 대로. 캠페인의 핵심 기능을 현재 진행중인 캠페인과 촉구대상자들로 좁히고. 특히 촉구 대상자를 정치권으로 좁혀서 정리해 보면 어떨까요? 촉구 대상자가 늘어나면 대상자 그룹 페이지를 늘려나가면서요.

첫화면은 현재 진행중인 캠페인을 카드뉴스 목록 형태로 좀 키워서 보여주고, 모바일에서 잘 보이게 바꾸고. 아래에 촉구 대상그룹 혹은 주요 촉구대상자 목록이 나오게 하구요.

메뉴도 두개만 남기는 걸로요.

또한 캠페인 생성시에 기본을 촉구로 놓고, 그 외의 기능은 문의 혹은 무언가를 더 눌러야 찾을수 있게 만들어도 좋겠습니다.

한번 논의해 보아요.

**Comment by wagurano** [comment]
기존의 프로젝트 페이지를 참고하여 만들어야겠군요.
카드 뉴스 만들기 https://tyle.io/developers#API 를 사용할 수 있으면 좋겠습니다.
이 외에도 유투브 동영상을 넣는 방법을 찾아보고 있습니다.

**Comment by dalikim** [comment]
이 이슈를 좀더 쪼개보는 것은 어떨까요?
