### ISSUE TITLE
촉구와 답변이 어떻게 이뤄지는지 촉구 대상자의 답변 아래에 설명을 추가합니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#71]

**Comment by gjkimpam** [comment]
이렇게 뜨는걸 말씀하신 거겠죠? 말풍선처럼 뜨니까 좋네요. 
![스크린샷 2019-12-04 오후 8 35 34](https://user-images.githubusercontent.com/35594166/70179285-b0e71200-16d5-11ea-91a3-f48cacc0dd33.png)
