### ISSUE TITLE
촉구 메일을 발송할때 전체 시스템의 순간 최대 발송량을 넘지 않게 적절히 배분하여 발송할 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#73]

**Comment by rest515** [comment]
한시간에 한번씩 묶어서 발송하는건 어떨까요.

**Comment by dalikim** [comment]
아 어떻게 할거냐면요. 촉구 대상이 같은 것은 여러게 묶어서 발송하려 합니다

**Comment by rest515** [comment]
1. 촉구 대상이 A, B, C 이면 메일을 발송할때 대상자를 같은 수신자로 하나의 메일로 같이 보낸다.
2. 촉구 대상이 A로 같은 여러개의 메일을 하나로 묶어서 보낸다. 1시간에 한번씩?

둘 중에 어느 것이려나요.

**Comment by dalikim** [comment]
1번 로직을 특정 시간마다 묶어서 발송합니다.

**Comment by rest515** [comment]
1,2번 모두 적용이네요.

**Comment by dalikim** [comment]
이건 제가 가져갈께요. 참여연이랑 이야기 하던게 있어서요.
