### ISSUE TITLE
모니터링을 도입합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#82]
참여연 등에서 캠페인 홍보를 하면 자주 서버가 다운되는데요.
skylight.io 를 설치해 보면 어떨까 합니다. 의견 주세요.

https://www.skylight.io/pricing

**Comment by wagurano** [comment]
다른 사례를 보니 멋집니다. https://oss.skylight.io/app/applications/K9H5IV3RqKGu/recent/6h/endpoints
설치하면 좋겠습니다.
