### ISSUE TITLE
촉구 대상자 중 답변한 사람을 더 강조해서 보여줍니다

### ISSUE THREAD

**Issue by rest515** [parti-coop/govcraft#87]

**Comment by dalikim** [comment]
촉구 대상 마다 촉구 받은 횟수가 비슷하네요. 촉구 대상자 중 가장 많이 촉구를 받은 사람을 강조하는 건 우선 미뤄 볼까해요. 필요하면 다른 이슈를 만들거나, 이 이슈를 다시 열면 어떨까해요.
