### ISSUE TITLE
캠페인을 임시 저장하고 오픈이 안된 채로 만들 수 있습니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#90]
숨겨진 캠페인의 경우 목록에만 나오지 않으면 될 듯합니다
그리고 오픈할 때 시작 날짜를 지정할 수 있도록 하면 합니다.
또한 오픈 직전에 참여 데이터 삭제 여부를 선택할 수 있게 해야겠습니다.

**Comment by wagurano** [comment]
> 숨겨진 캠페인의 경우 목록에만 나오지 않으면 될 듯합니다

캠페인 목록에서 숨기기 위해 데이터베이스에는 저장하고(캠페인 숫자 아이디 생김) 1) `published`와 같은 플래그 설정 + 2) 캠페인 만든 사람만 접근

>그리고 오픈할 때 시작 날짜를 지정할 수 있도록 하면 합니다.

앞서 설정한 `published` 플래그를 `false`에서 `true`와 바꿔주는 기능일까요? 이를테면 예약 문자/편지 보내기와 같은 걸까요?

> 또한 오픈 직전에 참여 데이터 삭제 여부를 선택할 수 있게 해야겠습니다.

참여 데이터 삭제는 어떤 경우인지 잘 모르겠습니다. @dalikim

**Comment by dalikim** [comment]
"또한 오픈 직전에 참여 데이터 삭제 여부를 선택할 수 있게 해야겠습니다" 요건 생각해 보니 그닥 필요없을 듯해요.

**Comment by gjkimpam** [comment]
확인했습니다. 미래 날짜로 입력할 경우 홈, 캠페인페이지에 노출되지 않더라고요. 

그런데 캠페인 개설창 자체에 입력할 것들이 많아서 이 임시저장 안내가 눈에 잘 안 들어오는 것 같아요. 
![스크린샷 2019-12-04 오후 8 27 11](https://user-images.githubusercontent.com/35594166/70178669-952f3c00-16d4-11ea-83da-c3fc7734601e.png)

- 시작일(선택) 근처에 마우스가 갈 때, 팝업 안내가 간다거나 
- (다음 버전에) 가장 직관적으로 저장 버튼 옆에 '임시저장' 버튼이 따로 마련되는 것이 좋을 것 같아요.

**Comment by dalikim** [comment]
@gjkimpam 다른 이슈를 떼 주시면 합니다.

**Comment by gjkimpam** [comment]
> @gjkimpam 다른 이슈를 떼 주시면 어떨까 합니다. 임시 저장 UX 보다는 캠페인 개설 자체 UX 문제거든요.

네, #138 로 제가 제안한 이슈는 옮겨뒀어요.
