### ISSUE TITLE
깃헙 release를 작성하면 실제 라이브로 배포됩니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/govcraft#99]
@rest515 @wagurano @iamswain25 어떨지 의견 바랍니다.
물론 원하면 그때그때 머지하면 바로 배포하고요.

**Comment by rest515** [comment]
저는 좋습니다. 그때그때 배포하는 것보다 훨씬 좋겠네요. 자정보다는 새벽이 더 좋을 거 같구요.

**Comment by dalikim** [comment]
여기 투표 기능 없나요? ㅋㅋ
몇 시가 좋을까요?

**Comment by rest515** [comment]
6시 정도면 어떨까요.

**Comment by iamswain25** [comment]
일어나서 에러 고치기 딱 좋은 시간이네요 ㅎㅎㅎ

**Comment by dalikim** [comment]
@rest515 @wagurano @iamswain25 https://union.parti.xyz/posts/31160 이 논의로 인해서 자동배포는 말고 https://github.com/parti-coop/govcraft/releases 여기서 특정 규칙으로 릴리즈하면 자동 배포하게 하겠습니다.

다른 의견 있으면 주세요.

**Comment by dalikim** [comment]
기본  브랜치를 다시 master로 바꿉니다.

**Comment by dalikim** [comment]
설정 끝났고요. 의견 없으면 이 이슈는 닫겠습니다.  https://github.com/parti-coop/govcraft/blob/master/.travis.yml
